# Generated by Django 4.2.2 on 2023-08-09 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('Game', 'Game'), ('Profile', 'Profile'), ('Site', 'Site'), ('Other', 'Other')], max_length=7)),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(10, message='Title must be at least 10 characters long!')])),
                ('description', models.TextField(help_text='Try to describe the problem in as much detail as possible!', max_length=500, validators=[django.core.validators.MinLengthValidator(50, message='Description must be at least 50 characters long!')])),
                ('video_image', models.URLField(blank=True, help_text='Please submit a link to a video and/or image that shows the problem, if you have one.', null=True)),
                ('creator', models.CharField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
