# Generated by Django 4.2.2 on 2023-08-10 08:50

import GameStats.Profile.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', validators=[GameStats.Profile.validators.image_size])),
                ('creator', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
