# Generated by Django 4.2.2 on 2023-08-11 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_staffchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StaffChat',
        ),
    ]
