# Generated by Django 4.2.2 on 2023-07-01 06:25

import GameStats.Profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='image',
            field=models.ImageField(default=None, upload_to='images', validators=[GameStats.Profile.validators.image_size]),
            preserve_default=False,
        ),
    ]
