# Generated by Django 4.2.2 on 2023-07-20 10:56

import GameStats.Profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_appuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[GameStats.Profile.validators.image_size]),
        ),
    ]
