# Generated by Django 4.2.4 on 2023-08-04 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(250, message="Comment can't be more than 250 characters long!")]),
        ),
    ]
